"""Change-driven commentary (spec §14) — PUBLIC-SAFE by design.

The narrative is generated ONCE per run by the daily GitHub Action using the repo's
own ANTHROPIC_API_KEY secret, then cached. The dashboard only ever *reads* the cached
text, so public users never trigger an API call — cost is ~1 cheap generation per day
regardless of traffic. The anthropic SDK is imported lazily so the public app doesn't
need it.

generate_commentary() — called by the Action (needs the key); writes commentary.md.
load_commentary()     — called by the dashboard (no key, no network).
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

import pandas as pd

from cte.adapters.base import read_cache
from cte.config import CACHE_DIR

_MD = CACHE_DIR / "commentary.md"
_META = CACHE_DIR / "commentary_meta.json"
_PREV = CACHE_DIR / "tension_map_prev.parquet"
_MODEL = os.environ.get("CTE_COMMENTARY_MODEL", "claude-haiku-4-5")

_SYSTEM = (
    "You are a macro strategist writing a terse daily note for a sophisticated FX "
    "trader. Use ONLY the data provided — never invent numbers, levels, or events. "
    "Be concrete and non-hedgy; it's fine to say the signal is mixed. No preamble, no "
    "disclaimers. ~180 words, markdown, this structure: a one-line regime read; 2-3 "
    "bullets on the currencies at inflection or the extremes of the map (say why, "
    "citing the pillar/overlay reason); one bullet on the standout carry pair; one "
    "line on what moved since the prior snapshot if given. Plain, professional."
)


def _fmt_quadrant(f: float, v: float) -> str:
    return (("improving" if f > 0 else "deteriorating") + " / " +
            ("stretched" if v > 0 else "cheap"))


def _build_context() -> str:
    tm = read_cache("tension_map")
    pillars = read_cache("pillar_scores")
    overlays = read_cache("overlays")
    warns = {}
    wp = CACHE_DIR / "warnings.json"
    if wp.exists():
        warns = json.loads(wp.read_text())

    lines = ["TENSION MAP (structural; fundamental, stretch):"]
    q = tm.set_index("ccy")
    for c in q.index:
        f = q.loc[c, "axis1_fundamental_struct"]; v = q.loc[c, "axis2_stretch_struct"]
        lines.append(f"  {c}: fund {f:+.2f}, stretch {v:+.2f}  [{_fmt_quadrant(f, v)}]")

    lines.append("\nPILLAR SCORES (signed; + = supportive/stretched):")
    lines.append(pillars.set_index("ccy").round(2).to_string())

    lines.append("\nOVERLAYS (yield regime, hike feasibility, carry crowding):")
    keep = [c for c in ["ccy", "yld_regime", "real10y_mult", "feasibility",
                        "infl_mult", "ctv_pctile"] if c in overlays.columns]
    lines.append(overlays[keep].to_string(index=False))

    if warns:
        lines.append("\nINFLECTION WARNINGS:")
        for c, notes in warns.items():
            lines.append(f"  {c}: " + " | ".join(n for n in notes))

    # what moved since last snapshot
    if _PREV.exists():
        prev = pd.read_parquet(_PREV).set_index("ccy")
        moves = []
        for c in q.index:
            if c in prev.index:
                df_ = q.loc[c, "axis1_fundamental_struct"] - prev.loc[c, "axis1_fundamental_struct"]
                dv = q.loc[c, "axis2_stretch_struct"] - prev.loc[c, "axis2_stretch_struct"]
                if abs(df_) > 0.15 or abs(dv) > 0.15:
                    moves.append(f"  {c}: fund {df_:+.2f}, stretch {dv:+.2f}")
        if moves:
            lines.append("\nCHANGE SINCE PRIOR SNAPSHOT:")
            lines.extend(moves)
    return "\n".join(lines)


def generate_commentary(model: str | None = None) -> str:
    """Generate + cache the daily note. Requires ANTHROPIC_API_KEY (Action only)."""
    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        raise RuntimeError("ANTHROPIC_API_KEY not set — commentary is generated only "
                           "by the daily Action, never by the public dashboard.")
    import anthropic  # lazy: public app never imports this
    context = _build_context()
    client = anthropic.Anthropic(api_key=key)
    msg = client.messages.create(
        model=model or _MODEL, max_tokens=700, system=_SYSTEM,
        messages=[{"role": "user", "content": context}])
    text = "".join(b.text for b in msg.content if getattr(b, "type", "") == "text")
    _MD.write_text(text)
    _META.write_text(json.dumps({
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "model": model or _MODEL}, indent=2))
    # snapshot current map for next run's change detection
    read_cache("tension_map").to_parquet(_PREV, index=False)
    return text


def load_commentary() -> tuple[str, dict]:
    """Read the cached note for the dashboard — no key, no network."""
    if not _MD.exists():
        return ("_Daily commentary is generated by the scheduled job; none cached "
                "yet._", {})
    meta = json.loads(_META.read_text()) if _META.exists() else {}
    return _MD.read_text(), meta


if __name__ == "__main__":
    if os.environ.get("ANTHROPIC_API_KEY"):
        print(generate_commentary())
    else:
        print("[dry run] no ANTHROPIC_API_KEY; context that WOULD be sent:\n")
        print(_build_context())
